//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class SalesDBEntities : DbContext
    {
        public SalesDBEntities()
            : base("name=SalesDBEntities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Product>()
                .Map(map =>
                {
                    map.Properties(p => new
                    {
                        p.ProductID,
                        p.Name,
                        p.Price,
                    });
                 });
            modelBuilder.Entity<Sale>()
                .Map(map =>
                {
                    map.Properties(p => new
                    {
                        p.SalesID,
                        p.SalesPersonID,
                        p.CustomerID,
                        p.ProductID,
                        p.Quantity,
                    });
                });
            modelBuilder.Entity<Inventory>()
                .Map(map =>
            {
                map.Properties(p => new
                {
                    p.ProductID,
                    p.Row,
                    p.Position,
                    p.Count,
                    p.TransactionDate,
                    p.LocationID,
                });
            });
            modelBuilder.Entity<Employee>()
                .Map(map =>
            {
                map.Properties(p => new
                {
                    p.EmployeeID,
                    p.FirstName,
                    p.MiddleInitial,
                    p.LastName,
                });
            });
            modelBuilder.Entity<Customer>()
                .Map(map =>
            {
                map.Properties(p => new
                {
                    p.CustomerID,
                    p.FirstName,
                    p.MiddleInitial,
                    p.LastName,
                });
            });
            base.OnModelCreating(modelBuilder);
        }

        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Inventory> Inventories { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Sale> Sales { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
